language: java
before_install:
  # Get some shared libs or else the SDK executables aren't found
  - sudo apt-get update -qq
  - sudo apt-get install -y ia32-libs ia32-libs-multiarch libgphoto2-2:i386 libsane:i386

  # Install what we need from the SDK
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar xzf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME="$(pwd)/android-sdk-linux"
  - export PATH="${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools"
  - android update sdk --no-ui --force --filter 1,5,36,48,49,50,51,52,53,54,55,56

  # Test straight away if the executables work
  - android
  - aapt

  # Install all that to Maven
  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd maven-android-sdk-deployer
  - mvn install -P 4.0.3
